version: '3'

services:
  mysql:
    image: mysql
    networks:
      - production-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: conta-digital

networks:
  production-network:
    driver: bridge